web/router.ex
defmodule Grid.Router do
  use Grid.Web, :router
  use Plug.ErrorHandler

  #Reports the exception and re-raises it
  defp handle_errors(conn = %{status: status}, %{kind: kind, reason: reason, stack: stack}) do
    message = Exception.format(:error, reason, stack)

    level = cond do
      status >= 500 -> :error
      status >= 400 -> :warning
      true -> :info
    end

    Rollbax.Client.emit(level, message, %{params: conn.params})
    Plug.Conn.WrapperError.reraise(conn, kind, reason)
  end

  alias Grid.Plugs

  pipeline :browser do
    if Mix.env == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.AssignUser
    plug Plugs.Kiosk
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Plugs.Kiosk
  end

  pipeline :admin do
    plug :put_layout, {Grid.LayoutView, "admin.html"}
    plug Plugs.AssignGoogleToken
    plug Plugs.Authenticate
  end

  pipeline :assign_vendor do
    plug Plugs.AssignModel, model: Grid.Vendor, param: "vendor_id"
    plug Plugs.Breadcrumb, resource: Grid.Vendor
  end
  pipeline :assign_vendor_activity do
    plug Plugs.AssignModel, model: Grid.VendorActivity, param: "vendor_activity_id",
      preload: :activity
    plug Plugs.Breadcrumb, resource: Grid.VendorActivity
  end
  pipeline :assign_product do
    plug Plugs.AssignModel, model: Grid.Product, param: "product_id"
    plug Plugs.Breadcrumb, resource: Grid.Product
  end
  pipeline :assign_product_price do
    plug Plugs.AssignModel, model: Grid.Price, param: "price_id"
    plug Plugs.Breadcrumb, resource: Grid.Price
  end
  pipeline :assign_activity do
    plug Plugs.AssignModel, model: Grid.Activity, param: "activity_id"
    plug Plugs.Breadcrumb, resource: Grid.Activity
  end
  pipeline :assign_amenity do
    plug Plugs.AssignModel, model: Grid.Amenity, param: "amenity_id"
    plug Plugs.Breadcrumb, resource: Grid.Amenity
  end

  scope "/", Grid do
    pipe_through :browser

    get "/", PageController, :index
    get "/about/terms", PageController, :tou
    get "/slideshow", PageController, :slideshow

    get "/vendors", VendorController, :index

    get "/vendor/accept/:vendor_token", OrderStatusController, :accept
    get "/vendor/reject/:vendor_token", OrderStatusController, :reject
    get "/vendor/status/:vendor_token", OrderStatusController, :vendor_status
    # put "/orders/:vendor_token/reject", OrderController, :reject
    # put "/orders/:customer_token/cancel/:id", OrderController, :cancel

    scope "/explore" do
      get "/shared_cart/:uuid", ExploreController, :shared_cart
      get "/*path", ExploreController, :index
    end

    get "/500", ErrorController, :render_500
    get "/404", ErrorController, :render_404
  end

  scope "/auth", Grid do
    pipe_through :browser

    get "/", AuthController, :index
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :login
    get "/:provider/callback", AuthController, :callback
  end

  scope "/web_api", Grid.Api, as: :api do
    pipe_through :api

    get "/activities", ActivityController, :index
    get "/activities/:id", ActivityController, :show

    put "/coupons", CouponController, :get_by_code

    get "/categories", CategoryController, :index
    get "/categories/:id", CategoryController, :show

    post "/checkout", CheckoutController, :checkout

    get "/date/:activity_slug/:category_slug",
      DateController, :first_experience_date

    get "/experiences", ExperienceController, :index
    get "/experiences/:id", ExperienceController, :show

    get "/products", ProductController, :index
    get "/products/:id", ProductController, :show

    get "/vendors", VendorController, :index
    get "/vendors/:id", VendorController, :show

    post "/orders", OrderController, :process_cart

    get "/shared_cart/:uuid", SharedCartController, :show
    post "/shared_cart", SharedCartController, :create
  end

  scope "/admin", Grid.Admin, as: :admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index

    get "/users", UserController, :index

    resources "/coupons", CouponController
    resources "/kiosks", KioskController
    resources "/slides", SlideController
    resources "/content_items", ContentItemController, [only: [:index, :edit, :update]]

    get "/orders/find_order_item", OrderController, :find_order_item
    resources "/orders", OrderController, [only: [:index, :show]]

    resources "/activities", ActivityController, [alias: Activity] do
      pipe_through :assign_activity

      resources "/amenities", AmenityController, [alias: Amenity] do
        pipe_through :assign_amenity

        resources "/amenity_options", AmenityOptionController
      end

      resources "/categories", CategoryController

      resources "/experiences", ExperienceController

      resources "/images", ImageController
      put "/images/:id/default", ImageController, :set_default
    end

    get "/vendors/refresh_all", VendorController, :refresh_all
    get "/vendors/:id/refresh", VendorController, :refresh
    resources "/vendors",   VendorController, [alias: Vendor] do
      pipe_through :assign_vendor

      resources "/activities", VendorActivityController, [except: [:edit, :update], alias: VendorActivity] do
        pipe_through :assign_vendor_activity
        resources "/seasons", SeasonController
      end

      resources "/locations", LocationController

      resources "/images", ImageController
      put "/images/:id/default", ImageController, :set_default

      get "/products/:id/clone", ProductController, :clone
      resources "/products", ProductController, [alias: Product] do
        pipe_through :assign_product

        resources "/start_times", StartTimeController

        resources "/images", ImageController
        put "/images/:id/default", ImageController, :set_default

        put "/prices/:id/default", PriceController, :set_default
        resources "/prices", PriceController, [alias: Price] do
          pipe_through :assign_product_price
          resources "/amounts", AmountController
        end
      end
    end
  end
end

web/views/layout_view.ex
defmodule Grid.LayoutView do
  use Grid.Web, :view
  import Phoenix.Controller, only: [controller_module: 1, get_flash: 2]

  alias Phoenix.Naming

  def nav_class(conn, controller) when is_atom(controller) do
    match = controller |> Naming.unsuffix("Controller")
    conn
    |> controller_module
    |> Atom.to_string
    |> String.starts_with?(match)
    |> if(do: "active", else: "")
  end

end

web/templates/layout/_admin_header.html.eex
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= @page_title || "Outpost" %>
  </h1>
</section>

web/templates/layout/_footer.html.eex
<%= unless assigns[:kiosk] do %>
<footer class="page-footer">
  <div class="row expanded">
    <div class="small-12 medium-3 columns text-center">
      <div class="logo image">
        <a href="/"><img src="/images/full-logo-450.png" alt="Outpost"></a>
      </div>
    </div>
    <div class="small-12 medium-6 columns text-center">
      <div class="creds">
        <span>Copyright &copy; 2016</span> &bull;
        <a href="http://outpostjh.com">Outpost Jackson Hole</a> &bull; <a href="https://goo.gl/maps/PndaX" target="_blank" >70 s. king street jackson, wyoming 83001</a> &bull;
        <a href="tel:3075904790"><span class="flaticon-telephone5"></span>(307) 690-4790</a> &bull;
        <a href="mailto:info@outpostjh.com"><span class="flaticon-envelope54"></span>info@outpostjh.com</a>
        <div class="outpost-login"><div><a href="http://www.outpostjh.com/owners-portal/" >Owner Login</a></div></div>
      </div>
    </div>
    <div class="small-12 medium-3 columns">
      <%= if assigns[:is_home] do %>
      <% # @TODO make this only appear on home and experience pages, not other explore pages %>
      <div class="row align-stretch align-center tripadvisor-logo text-center small-collapse">
        <div class="columns small-7 medium-10 large-7">Ratings and Reviews powered by</div>
        <div class="columns small-7 medium-10 large-7"><img src="<%= static_path(Grid.Endpoint, "/images/tripadvisor.png") %>"/></div>
        <div class="columns small-7 medium-10 large-7"><a href="http://tripadvisor.com/pages/terms.html">&copy; TripAdvisor 2015</a></div>
      </div>
      <% end %>
    </div>
  </div>
</footer>
<% end %>

web/templates/layout/_footer_scripts.html.eex
<script src="<%= static_path(Grid.Endpoint, "/js/vendor.js") %>"></script>
<script src="<%= static_path(Grid.Endpoint, "/js/app.js") %>"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', '<%= Grid.fetch_env!(:google_tracking_id) %>', 'auto');

  <%= if !assigns[:spa] do %>
  ga('send', 'pageview');
  <% end %>
</script>

<%= unless assigns[:hide_purechat] do %>
  <script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '26ac2763-4a07-4ff8-9d4a-b2ccadd51fb1', f: true }); done = true; } }; })();</script>

  <div class="how-it-works-button-outer">
    <p class="how-it-works-button"><a data-open="how-it-works" class="button">How it Works</a></p>
  </div>
<% end %>

web/templates/layout/_head_scripts.html.eex
<link rel="stylesheet" href="<%= static_path(Grid.Endpoint, "/css/app.css") %>">
<link rel="icon" href="<%= static_path(Grid.Endpoint, "/images/favicon.ico") %>" type="image/gif" sizes="16x16">
<script src="https://use.typekit.net/fal4rbd.js"></script>
<script>try{Typekit.load({ async: false });}catch(e){}</script>

web/templates/layout/_header.html.eex
<header class="page-header">
  <div class="full-width small-collapse" >
    <div class="title-bar hide-for-xlarge">
      <%= unless assigns[:kiosk] do %>
        <button type="button" class="menu-icon" data-toggle="offCanvas"></button>
      <% end %>
      <div class="logo"><a href="/">Outpost</a></div>
    </div>
    <div class="top-bar show-for-xlarge" id="outpostMenu" >
      <div class="top-bar-left">
        <ul class="menu" >
          <li class="logo"><a href="/">Outpost</a></li>
          <%= unless assigns[:kiosk] do %>
            <li><a href="http://www.outpostjh.com/rentals/">Lodging</a></li>
            <li><%= link "Activities", to: explore_path(Grid.Endpoint, :index, ["activities"]), class: assigns[:activities_class] %></li>
            <li><a href="http://www.outpostjh.com/trip-planning/">Trip Planning</a></li>
            <li><a href="http://itswhatwedohere.com">Journal</a></li>
            <li><a href="http://www.outpostjh.com/outpost/">About Us</a></li>
          <% end %>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><a class="telephone-cta" href="tel:3076904790"><span>Questions? Call Us!</span><span>307.690.4790</span></a></li>
          <%= unless assigns[:kiosk] do %>
          <li><a class="button hollow" href="http://www.outpostjh.com/property-management/">List Your Property</a></li>
          <% end %>
          <li><%= link to: explore_path(Grid.Endpoint, :index, ["cart"]), class: "flaticon-cart fi shopping-cart" do %>&nbsp;<% end %></li>
        </ul>
      </div>
    </div>
  </div>
  <%= render "_how_it_works.html", kiosk: assigns[:kiosk] %>
</header>

web/templates/layout/_how_it_works.html.eex
<div class="how-it-works reveal large" id="how-it-works" >
  <div class="row expanded">
    <div class="columns text-right close-section">
      <button class="close-button" aria-label="Close alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  <div class="show-for-large">
    <div class="row align-spaced align-middle">
      <%= unless @kiosk do %>
      <div class="columns small-12 medium-4 large-3 text-center">
        <a class="full-box-link" href="http://www.outpostjh.com/rentals/">
          <div class="image-house image"></div>
          <p class="lead">Find a Place to Stay</p>
          <p>Browse our homes and book your outpost in Jackson Hole. Look through our portfolio.</p>
        </a>
      </div>
      <% end %>
      <div class="columns small-12 medium-4 large-3 text-center">
        <a class="full-box-link" href="<%= explore_path(Grid.Endpoint, :index, ["activities"]) %>">
          <div class="image-activities image"></div>
          <p class="lead">Book Activities</p>
          <p>Plan your Jackson Hole adventure by discovering new activities, comparing vendors side-by-side, and booking your whole itinerary online.</p>
        </a>
      </div>
      <div class="columns small-12 medium-4 large-3 text-center">
        <a class="full-box-link" href="mailto:book@outpostjh.com">
          <div class="image-assistant image"></div>
          <p class="lead">Or, Let us Do the Work</p>
          <p>Tired of researching and planning? Chat with us — we’ll point you in the right direction and book activities, lodging, or restaurants for you at no extra cost.</p>
        </a>
      </div>
    </div>
    <div class="row align-center align-middle">
      <p class="columns small-12 lead text-center">All activities and Outpost services come at no extra cost to you.</p>
    </div>
    <div class="row align-middle">
      <div class="columns small-12 text-right"><button type="button" class="button hollow" data-close>Got it!</button></div>
    </div>
  </div>
  <div class="hide-for-large" >
    <div class="row hide-for-medium">
      <div class="columns small-12 text-center">
        <p class="lead">How it Works</p>
      </div>
    </div>
    <div class="orbit" id="how-orbit" role="region" aria-label="How It Works" >
      <ul class="orbit-container">
        <%= unless @kiosk do %>
          <li class="is-active orbit-slide text-center">
            <a class="full-box-link" href="http://www.outpostjh.com/rentals/">
              <div class="image-house image"></div>
              <div class="orbit-text" >
                <p class="lead">Find a Place to Stay</p>
                <p>Browse our homes and book your outpost in Jackson Hole. Look through our portfolio.</p>
              </div>
            </a>
            <div class="row align-middle bottom-row">
              <div class="columns small-12 text-right"><p class="fa fa-long-arrow-right"></p><p>Swipe to Continue</p></div>
            </div>
          </li>
        <% end %>
        <li class="orbit-slide text-center">
          <a class="full-box-link" href="<%= explore_path(Grid.Endpoint, :index, ["activities"]) %>">
            <div class="image-activities image"></div>
            <div class="orbit-text" >
              <p class="lead">Book Activities</p>
              <p>Plan your Jackson Hole adventure by discovering new activities, comparing vendors side-by-side, and booking your whole itinerary online.</p>
            </div>
          </a>
        </li>
        <li class="orbit-slide text-center">
          <a class="full-box-link" href="mailto:book@outpostjh.com">
            <div class="image-assistant image"></div>
            <div class="orbit-text" >
              <p class="lead">Or, Let us Do the Work</p>
              <p>Tired of researching and planning? Chat with us — we’ll point you in the right direction and book activities, lodging, or restaurants for you at no extra cost.</p>
            </div>
          </a>
          <div class="row align-middle bottom-row">
            <div class="columns small-12 text-right"><button type="button" class="button hollow" data-close>Got it!</button></div>
          </div>
        </li>
      </ul>
      <nav class="orbit-bullets">
        <%= unless @kiosk do %>
        <button class="is-active" data-slide="0"><span class="show-for-sr">Vacation Rentals.</span></button>
        <% end %>
        <button data-slide="1"><span class="show-for-sr">Book Activities.</span></button>
        <button data-slide="2"><span class="show-for-sr">Concierge Services.</span></button>
      </nav>
    </div>
  </div>
</div>

web/templates/layout/_off_canvas_menu.html.eex
<div class="off-canvas position-left" id="offCanvas" data-off-canvas>
  <ul class="mobile-ofc vertical menu" >
    <li class="menu-text"><a href="/">Home</a></li>
    <%= unless assigns[:kiosk] do %>
    <li class="menu-text"><a href="http://www.outpostjh.com/rentals/">Lodging</a></li>
    <% end %>
    <li class="menu-text"><%= link "Activities", to: explore_path(Grid.Endpoint, :index, ["activities"]) %></li>
    <%= unless assigns[:kiosk] do %>
    <li class="menu-text"><a href="http://www.outpostjh.com/trip-planning/">Trip Planning</a></li>
    <li class="menu-text"><a href="http://www.outpostjh.com/itswhatwedohere">Journal</a></li>
    <li class="menu-text"><a href="http://www.outpostjh.com/outpost/">About Us</a></li>
    <li class="menu-text"><a href="http://www.outpostjh.com/property-management/">List Your Property</a></li>
    <% end %>
    <li class="menu-text"><%= link to: explore_path(Grid.Endpoint, :index, ["cart"]), class: "flaticon-cart fi" do %>&nbsp;<% end %></li>
  </ul>
</div>

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin | Outpost | Jackson Hole eConcierge</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin.css") %>">
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img alt="OUTPOST" src="/images/barn-transparent.png">
          </a>
          <p class="navbar-text">Admin: <%= Grid.AdminView.environment_tag %></p>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <p class="navbar-text"><%= @current_user.email %></p>
              <a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= if @current_user.image do %>
                <img src="<%= @current_user.image %>">
                <% else %>
                <span class="glyphicon glyphicon-user"></span>
                <% end %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li class="info">
                    <%= link "Log Out", to: auth_path(@conn, :logout) %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="<%= nav_class(@conn, Grid.Admin.DashboardController) %>">
              <%= link "Dashboard", to: admin_dashboard_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.ContentItemController) %>">
              <%= link "Content Management", to: admin_content_item_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.ActivityController) %>">
              <%= link "Activities", to: admin_activity_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.VendorController) %>">
              <%= link "Vendors", to: admin_vendor_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.UserController) %>">
              <%= link "Users", to: admin_user_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.OrderController) %>">
              <%= link "Orders", to: admin_order_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.CouponController) %>">
              <%= link "Coupons", to: admin_coupon_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.KioskController) %>">
              <%= link "Kiosks", to: admin_kiosk_path(@conn, :index) %>
            </li>
            <li class="<%= nav_class(@conn, Grid.Admin.SlideController) %>">
              <%= link "Slides", to: admin_slide_path(@conn, :index) %>
            </li>
          </ul>
        </div>
        <div class="col-xs-10 col-sm-10 col-xs-offset-2 col-sm-offset-2 col-md-10 col-md-offset-2 main">
          <ol class="breadcrumb">
          <%=
            breadcrumbs = Grid.Admin.BreadcrumbsView.breadcrumbs(@conn)
            if breadcrumbs == [] do
              Grid.Admin.BreadcrumbsView.crumb("Dashboard")
            else
              for breadcrumb <- breadcrumbs do
                Grid.Admin.BreadcrumbsView.crumb(breadcrumb)
              end
            end
          %>
          </ol>
          <%= render "_admin_header.html", page_title: assigns[:page_title] %>

          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Outpost | Jackson Hole eConcierge</title>
    <%= render "_head_scripts.html" %>
  </head>

  <body<%= if assigns[:kiosk], do: ~E( class="kiosk") %>>
    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
        <%= render "_off_canvas_menu.html", assigns %>
        <div class="off-canvas-content" data-off-canvas-content>
          <%= render "_header.html", assigns %>

          <%= render @view_module, @view_template, assigns %>

          <%= render "_footer.html", assigns %>
        </div>
      </div>
    </div>
    <%= render "_footer_scripts.html", assigns %>
  </body>
</html>