web/router.ex
defmodule Grid.Router do
  use Grid.Web, :router
  use Plug.ErrorHandler

  #Reports the exception and re-raises it
  defp handle_errors(conn = %{status: status}, %{kind: kind, reason: reason, stack: stack}) do
    message = Exception.format(:error, reason, stack)

    level = cond do
      status >= 500 -> :error
      status >= 400 -> :warning
      true -> :info
    end

    Rollbax.Client.emit(level, message, %{params: conn.params})
    Plug.Conn.WrapperError.reraise(conn, kind, reason)
  end

  alias Grid.Plugs

  pipeline :browser do
    if Mix.env == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.AssignUser
    plug Plugs.Kiosk
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Plugs.Kiosk
  end

  pipeline :admin do
    plug :put_layout, {Grid.LayoutView, "admin.html"}
    plug Plugs.AssignGoogleToken
    plug Plugs.Authenticate
  end

  pipeline :assign_vendor do
    plug Plugs.AssignModel, model: Grid.Vendor, param: "vendor_id"
    plug Plugs.Breadcrumb, resource: Grid.Vendor
  end
  pipeline :assign_vendor_activity do
    plug Plugs.AssignModel, model: Grid.VendorActivity, param: "vendor_activity_id",
      preload: :activity
    plug Plugs.Breadcrumb, resource: Grid.VendorActivity
  end
  pipeline :assign_product do
    plug Plugs.AssignModel, model: Grid.Product, param: "product_id"
    plug Plugs.Breadcrumb, resource: Grid.Product
  end
  pipeline :assign_product_price do
    plug Plugs.AssignModel, model: Grid.Price, param: "price_id"
    plug Plugs.Breadcrumb, resource: Grid.Price
  end
  pipeline :assign_activity do
    plug Plugs.AssignModel, model: Grid.Activity, param: "activity_id"
    plug Plugs.Breadcrumb, resource: Grid.Activity
  end
  pipeline :assign_amenity do
    plug Plugs.AssignModel, model: Grid.Amenity, param: "amenity_id"
    plug Plugs.Breadcrumb, resource: Grid.Amenity
  end

  scope "/", Grid do
    pipe_through :browser

    get "/", PageController, :index
    get "/about/terms", PageController, :tou
    get "/slideshow", PageController, :slideshow

    get "/vendors", VendorController, :index

    get "/vendor/accept/:vendor_token", OrderStatusController, :accept
    get "/vendor/reject/:vendor_token", OrderStatusController, :reject
    get "/vendor/status/:vendor_token", OrderStatusController, :vendor_status
    # put "/orders/:vendor_token/reject", OrderController, :reject
    # put "/orders/:customer_token/cancel/:id", OrderController, :cancel

    scope "/explore" do
      get "/shared_cart/:uuid", ExploreController, :shared_cart
      get "/*path", ExploreController, :index
    end

    get "/500", ErrorController, :render_500
    get "/404", ErrorController, :render_404
  end

  scope "/auth", Grid do
    pipe_through :browser

    get "/", AuthController, :index
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :login
    get "/:provider/callback", AuthController, :callback
  end

  scope "/web_api", Grid.Api, as: :api do
    pipe_through :api

    get "/activities", ActivityController, :index
    get "/activities/:id", ActivityController, :show

    put "/coupons", CouponController, :get_by_code

    get "/categories", CategoryController, :index
    get "/categories/:id", CategoryController, :show

    post "/checkout", CheckoutController, :checkout

    get "/date/:activity_slug/:category_slug",
      DateController, :first_experience_date

    get "/experiences", ExperienceController, :index
    get "/experiences/:id", ExperienceController, :show

    get "/products", ProductController, :index
    get "/products/:id", ProductController, :show

    get "/vendors", VendorController, :index
    get "/vendors/:id", VendorController, :show

    post "/orders", OrderController, :process_cart

    get "/shared_cart/:uuid", SharedCartController, :show
    post "/shared_cart", SharedCartController, :create
  end

  scope "/admin", Grid.Admin, as: :admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index

    get "/users", UserController, :index

    resources "/coupons", CouponController
    resources "/kiosks", KioskController
    resources "/slides", SlideController
    resources "/content_items", ContentItemController, [only: [:index, :edit, :update]]

    get "/orders/find_order_item", OrderController, :find_order_item
    resources "/orders", OrderController, [only: [:index, :show]]

    resources "/activities", ActivityController, [alias: Activity] do
      pipe_through :assign_activity

      resources "/amenities", AmenityController, [alias: Amenity] do
        pipe_through :assign_amenity

        resources "/amenity_options", AmenityOptionController
      end

      resources "/categories", CategoryController

      resources "/experiences", ExperienceController

      resources "/images", ImageController
      put "/images/:id/default", ImageController, :set_default
    end

    get "/vendors/refresh_all", VendorController, :refresh_all
    get "/vendors/:id/refresh", VendorController, :refresh
    resources "/vendors",   VendorController, [alias: Vendor] do
      pipe_through :assign_vendor

      resources "/activities", VendorActivityController, [except: [:edit, :update], alias: VendorActivity] do
        pipe_through :assign_vendor_activity
        resources "/seasons", SeasonController
      end

      resources "/locations", LocationController

      resources "/images", ImageController
      put "/images/:id/default", ImageController, :set_default

      get "/products/:id/clone", ProductController, :clone
      resources "/products", ProductController, [alias: Product] do
        pipe_through :assign_product

        resources "/start_times", StartTimeController

        resources "/images", ImageController
        put "/images/:id/default", ImageController, :set_default

        put "/prices/:id/default", PriceController, :set_default
        resources "/prices", PriceController, [alias: Price] do
          pipe_through :assign_product_price
          resources "/amounts", AmountController
        end
      end
    end
  end
end

web/templates/page/activity.html.eex
<div class="page activity">
  <div class="top-row ">
    <header class="page-head" >
      <div class="row column">
        <h1><%= @selected_activity.name %></h1>
        <p><%= @selected_activity.description %></p>
      </div>
    </header>
  </div>
  <div class="search-bar">
    <div class="row column">
      <%= form_for @conn, page_path(@conn, :activity), [as: :activity, id: "search_form", method: "get", enforce_utf8: false], fn f -> %>
        <div class="row small-collapse">
          <div class="input-group">
            <%= select(
              f, :id,
              Enum.map(@activities, &({&1.name, &1.id})),
              [ class: "input-group-field chosen-select",
                "data-placeholder": "Rafting, Hiking, Biking, etc.",
                prompt: "",
                value: @selected_activity.id,
                id: :activity_select
              ])
            %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row column top-categories">
    <ul class="menu">
      <li><a class="active" href="#">Half Day</a></li>
      <li><a href="#">Full Day</a></li>
      <li><a href="#">Overnight</a></li>
      <li><a href="#">Classes</a></li>
    </li>
  </div>
  <div class="row small-up-1 medium-up-2 large-up-3">
    <%= for vendor <- @selected_activity.vendors do %>
      <div class="column">
        <img src="/images/rental.jpg" alt="Home Rentals">
        <p class="lead"><%= vendor.name %></p>
        <p><a href="#" class="more-info">View More Info</a></p>
      </div>
    <% end %>
  </div>
  <div class="row column activity-bottom">
    <h2>Others Have Also Booked</h2>
  </div>
  <div class="row small-up-1 medium-up-2 large-up-3 overlays">
    <div class="column">
        <p class="overlay-text">Rafting</p>
        <img src="/images/rental.jpg" alt="Rafting">
    </div>
    <div class="column">
        <p class="overlay-text">Play House</p>
        <img src="/images/margarita.jpg" alt="Play House">
    </div>
    <div class="column">
        <p class="overlay-text">Wildlife Tours</p>
        <img src="/images/tour-van.jpg" alt="Wildlife Tours">
    </div>
  </div>
</div>

web/templates/page/index.html.eex
<div class="full-overlay-select-list-container home" id="full-overlay-select-list-container">
  <ul>
    <%= unless assigns[:kiosk] do %>
    <li><%= link "Lodging", to: "http://www.outpostjh.com/rentals/" %></li>
    <% end %>
    <li><%= link "All Activities", to: explore_path(@conn, :index, ["activities"]), class: "selected" %></li>
    <%= for activity <- @available_activities do %>
      <li><%= link activity.name, to: explore_path(@conn, :index, [activity.slug, "categories"]) %></li>
    <% end %>
  </ul>
  <div class="full-overlay-black-overlay"></div>
</div>
<div class="home page">
  <section class="top-row small-collapse home-main expanded row">
    <div class="darken-overlay"></div>
    <div class="row align-center align-middle home-main-inner expanded">
      <div class="small-12 columns search-bar" >
        <div class="row small-collapse align-center expanded">
          <div class="small-12 columns">
            <div class="search-label">
              <%= Grid.ContentView.get("Homepage", "Search Title", "Book Your Adventure in Jackson Hole") %>
            </div>
          </div>
          <div class="small-12 medium-10 large-8 columns form-group">
            <label for="activity[id]">Explore</label>
            <div class="input-group-field">
              <div class="full-overlay-select-opener" tabindex="0">
                <span class="current">All Activities</span>
              </div>
            </div>
            <div class="input-group-button">
              <%= link "Go", to: explore_path(@conn, :index, ["activities"]), class: "button" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= unless assigns[:kiosk] do %>
  <section class="home-middle">
    <header class="row align-center">
      <div class="column small-12 large-10">
        <div class="section-title small-12 column">
          <%= Grid.ContentView.get("Homepage", "Intro Title", "Jackson Hole Trip Planners") %>
        </div>
        <div class="section-subtitle small-12 column">
          <%= Grid.ContentView.get("Homepage", "Intro Tagline", "Search, discover and book experiences or simply ask. Contact us for advice!") %>
        </div>
      </div>
    </header>
    <div class="row overlays align-center">
      <div class="small-12 large-11 columns">
        <div class="row align-center align-stretch">
          <div class="column custom-column-map">
            <a target="_blank" href="https://www.google.com/maps/place/Outpost/@43.4787252,-110.7627985,17z/data=!3m1!4b1!4m5!3m4!1s0x53531a42ec7bbce7:0xa4c2b12be99be183!8m2!3d43.4787252!4d-110.7606098">
              <div class="cta-card map-cta">
                <div class="darken-overlay-hover"></div>
                <img src="/images/Map_cropped.jpg">
              </div>
            </a>
          </div>
          <div class="column custom-column-contact">
            <div class="contact-us-cta">
              <p class="lead">Contact Us for Advice!</p>
              <p class="push-down">You can either search and book experiences on your own, or we can help you to plan your itinerary.</p>
              <div class="row bottom align-center">
                <a class="small" href="tel:3076904790"><span class="home-telephone">307.690.4790</span></a>
                <a class="small" href="mailto:concierge@outpostjh.com"><span class="home-email">concierge@outpostjh.com</span></a>
              </div>
            </div>
          </div>
          <div class="column small-12 medium-8">
            <a href="http://www.outpostjh.com/rentals/">
              <div class="double-wide rentals-cta">
                <div class="darken-overlay"></div>
                <div class="overlay-text">
                  <p>Vacation Rentals</p>
                  <p class="small">Book Your stay in Jackson Hole</p>
                </div>
                <p class="booking-button">Book Now</p>
              </div>
            </a>
          </div>
          <div class="column small-12 medium-4">
            <a href="<%= explore_path(@conn, :index, ["staff_picks"]) %>">
              <div class="single-wide staff-picks-cta">
                <div class="darken-overlay"></div>
                <div class="overlay-text">
                  <p>Outpost Staff Picks</p>
                  <p class="small">Book Our Favorite Experiences</p>
                </div>
                <p class="booking-button">
                    Learn More
                </p>
              </div>
            </a>
          </div>
          <div class="column small-12 medium-4 align-center align-middle">
            <a class="dark-green big-button text-center align-middle" href="<%= vendor_path(@conn, :index) %>">
              <div class="overlay-text">
                <p >Our Partners</p>
                <p class="small">Read about our vendors</p>
              </div>
            </a>
          </div>
          <div class="column small-12 medium-8">
            <a href="http://www.outpostjh.com/jackson-hole-concierge-services/">
              <div class="double-wide concierge-cta">
                <div class="darken-overlay"></div>
                <div class="overlay-text">
                  <p>Free Trip Planning Services</p>
                  <p class="small">Tired of Researching &amp; Planning? We can Help</p>
                </div>
                <p class="booking-button">
                    Read More
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="home-bottom">
    <header class="row align-center">
      <div class="column small-12 large-10">
        <div class="section-title small-12 column">
          <%= Grid.ContentView.get("Homepage", "Articles Title", "Things to Do in Jackson Hole") %>
        </div>
        <div class="section-subtitle small-12 column">
          <%= Grid.ContentView.get("Homepage", "Articles Tagline", "Contact us for any questions at all!") %>
        </div>
      </div>
    </header>
    <div class="row align-center align-stretch" data-equalizer data-equalize-on="medium">
      <%= for {article, index} <- Enum.with_index(@articles) do %>
        <%= if index == 4, do: raw("</div><div class='row align-center' data-equalizer data-equalize-on='medium'>") %>
        <%= if index < 4 do %>
          <div class="column small-12 medium-6" >
            <a class="home-article-large" href="<%= article["link"] %>" data-equalizer-watch>
        <% else %>
          <div class="column small-12 medium-4" >
            <a href="<%= article["link"] %>" data-equalizer-watch>
        <% end %>
            <img src="<%= article["featured_image_url"] %>" alt="<%= get_in(article, ["title", "rendered"]) |> raw %>">
            <p class="lead"><%= get_in(article, ["title", "rendered"]) |> raw %></p>
            <p class="subheader"><%= raw(article["_outpost_subtitle"]) %></p>
            <p class="article-link">Learn More</p>
          </a>
        </div>
      <% end %>
    </div>
    <div class="row column text-center">
      <a href="http://www.outpostjh.com/trip-planning" class="bottom-link"><%= Grid.ContentView.get("Homepage", "View All Articles Link Text", "View All Jackson Hole Trip Planning Articles") %></a>
    </div>
  </section>
  <% end %>
</div>

web/templates/page/slideshow.html.eex
<div class="orbit kiosk-slideshow" id="kiosk-orbit" role="region" aria-label="Book Activities in Jackson Hole" >
  <div class="slide-to-activities">
    <%= link to: explore_path(@conn, :index, ["activities"]), class: "button", id: "link-all-activities" do %>
    Tap Here for More Activities
    <% end %>
  </div>
  <ul class="orbit-container">
    <button class="orbit-previous fi flaticon-arrow-left"><span class="show-for-sr">Previous Slide</span></button>
    <button class="orbit-next fi flaticon-arrow-right"><span class="show-for-sr">Next Slide</span></button>
    <%= for slide <- @kiosk.slides do %>
    <li class="orbit-slide" style="background-image: url(<%= slide.photo_url %>)">
      <a href="<%= kiosk_url(@kiosk, slide.action_link) %>" class="slide" data-category="Kiosk:<%= @kiosk.id %>:Slideshow" data-slide-id="<%= slide.id %>">
        <img src="<%= slide.photo_url %>" />
        <%= if slide.title do %>
          <div class="orbit-caption">
            <%= if slide.title_label do %>
              <header><%= slide.title_label %></header>
            <% end %>
            <main>
              <p><%= slide.title %></p>
              <span class="button action-button"><%= slide.action_label %></span>
            </main>
          </div>
        <% else %>
          <div class="button lower-right action-button"><%= slide.action_label %></div>
        <% end %>
      </a>
    </li>
    <% end %>
  </ul>
</div>

web/templates/page/tou.html.eex
<div class="page">
  <div class="top-row">
    <h2 class="page-title">Outpost Terms of Service Agreement</h2>
  </div>
  <div class="row align-center">
    <p class="column small-12 medium-9 large-7">THE FINE PRINT</p>

    <p class="column small-12 medium-9 large-7">This Terms of Service Agreement (the “Agreement”) is an agreement between you (the “User”) and Outpost JH, Inc. (“Outpost, “we” or “us”).  We provide Users with access to providers of goods and services as well as a means to book or reserve those goods and services for purchase or rent (collectively, the “Goods/Services”).</p>

    <p class="column small-12 medium-9 large-7">We have tried to keep this Agreement as readable and straightforward as possible.  If you have suggestions that can help us improve it or any questions about the agreement, please email us [hyperlink] and let us know.  This Agreement explains our obligations to you, and your obligations to us.  This agreement is the entire agreement between you and us.  By using the Outpost platform in any way, you are agreeing to comply with these Terms and any other legal notices, conditions or guidelines posted on our website or mobile app.</p>

    <p class="column small-12 medium-9 large-7"><b>Privacy.</b> We will protect and keep confidential your contact information.  We will only share that information with the Vendors with whom you book, reserve, or purchase (“Book”) Goods/Services and only to the extent necessary for the Vendors to provide you with the Goods/Services.  Your payment information is not saved by Outpost or the Vendors and it will not be shared with anyone. It is encrypted using SSL technology, processed and stored on secure servers by our third party payment service provider.   </p>

    <p class="column small-12 medium-9 large-7"><b>Additional Charges.</b> If once you Book Goods/Services you desire any add-ons or extras or purchase any insurance or damage waiver or similar extras, you will have to negotiate and pay the Vendor directly for those items on the day of use/purchase.</p>

    <p class="column small-12 medium-9 large-7"><b>Description of Goods/Services.</b> The descriptions of Goods/Services are as accurate as possible, though they may not be 100% error free and some Goods/Services may change or evolve over time. We and our Vendors will do our best to ensure the descriptions are as accurate as possible, but you acknowledge this is an imperfect science.</p>

    <p class="column small-12 medium-9 large-7"><b>Liability </b>Waiver.  Outpost is a middleman, we are not responsible for the actual Good/Services.  We try hard to select reputable Vendors to provide the User with quality Goods/Services, but in the end, we are not responsible or liable for the acts or omissions of our Vendors.  WE ARE NOT LIABLE TO YOU OR ANY OTHER PERSON FOR ANY DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION ANY PUNITIVE, EXEMPLARY, CONSEQUENTIAL, INCIDENTAL, INDIRECT OR SPECIAL DAMAGES (INCLUDING BUT NOT LIMITED TO, ANY PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, AND BUSINESS INTERRUPTION) ARISING FROM OR IN CONNECTION WITH THE USE OF THE OUTPOST PLATFORM, WEBSITE OR MOBILE APP AND/OR THE GOODS/SERVICES OF THIRD PARTY VENDORS).  AS A RESULT, YOU HEREBY RELEASE OUTPOST AND HOLD OUTPOST AND ITS PARENTS, SUBSIDIARIES, AFFILIATES, AND THEIR OFFICERS, DIRECTORS, TRUSTEES, SUBCONTRACTORS, AGENTS AND EMPLOYEES, HARMLESS FROM ALL CLAIMS, DEMANDS, AND DAMAGES OF ANY KIND, KNOWN AND UNKNOWN, SUSPECTED AND UNSUSPECTED, DISCLOSED AND UNDISCLOSED ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE OUTPOST PLATFORM, THE MOBILE APP AND THE USE OF GOODS/SERVICES PROVIDED BY THIRD PARTY VENDORS AND YOU HEREBY WAIVE THE PROVISIONS OR ANY STATE OR LOCAL LAW LIMITING OR PROHIBITING A GENERAL RELEASE</p>

    <p class="column small-12 medium-9 large-7"><b>Indemnity.</b>  You agree to indemnify and hold us and our parents, subsidiaries, affiliates, and their officers, directors, trustees, subcontractors, agents and employees (“Indemnified Parties”) from and against all liability, loss, claim, damage, expense, cost (including but not limited to attorneys’ fees), incurred by or made against the Indemnified Parties in connection with any claim arising from or related to the Outpost platform, website or mobile app and/or the goods/services of third party vendors.  Each Indemnified Party may, at its election, assume the defense and control of any matter for which it is indemnified hereunder.  You shall not settle any matter involving an Indemnified Party without the consent of the applicable Indemnified Party. </p>

    <p class="column small-12 medium-9 large-7"><b>Cancellation period.</b>  Unless stated otherwise at the time you make your reservation, there is a 48 hour cancellation period.  If you cancel more than 48 hours prior to the time you are scheduled to use/receive the Goods/Services, you will be refunded all of your money.  If you cancel 48 hours or less prior to the time you are scheduled to use/receive the Goods/Services, you will forfeit all amounts paid.</p>

    <p class="column small-12 medium-9 large-7"><b>Payment.</b>  At the time you submit a request to Book, your credit card will not be charged. Your payment information will be kept secure and verified by our third party payment service provider. Payment will only be charged in the full amount for the Goods/Services, after the booking is confirmed by the Vendor. You will receive a confirmation email and receipt at the time this booking confirmation and transaction take place.</p>

    <p class="column small-12 medium-9 large-7"><b>Refunds.</b>  If you are entitled to a refund, we will do our best to refund your credit card the same day.  At times, it can take up to three business days to process these refunds but we try to refund you all amounts due as soon as possible.</p>

    <p class="column small-12 medium-9 large-7"><b>Act of god.</b>  Certain things are deemed “Acts of God”.  This not a religious term, but a legal term for events outside of human control such as natural disasters, labor shortages, weather, etc. for which no one can be held responsible.  Our Vendors strive to honor each and every reservation, however, some things are out of their hands.  An example of an Act of God that is out of our Vendors’ hands which they cannot control and which may affect your Booking is weather.  For example, if you booked a hot air balloon ride, the wind must be below a certain threshold.  If the wind rises above that threshold, the balloon cannot safely be operated and a Vendor will cancel your reservation and you will be refunded in full.  Another example is scenic flights.  While planes can fly in cloud cover, the scenic experience will be very adversely affected if you cannot see our beautiful valley.  Our vendors want you to have a good experience and taking a scenic flight in the clouds is unlikely to be a good experience and those types of flights will be cancelled on account of poor weather.</p>

    <p class="column small-12 medium-9 large-7"><b>Notice of Change.</b> In the unfortunate and unforeseen event that your Booking is altered, we will inform you as soon as possible, suggest possible alternative Goods/Services and if nothing suitable is found, refund your entire payment.</p>

    <p class="column small-12 medium-9 large-7"><b>Amendments.</b>  We reserve the right, in our sole discretion, to modify or replace any part of this Agreement, at any time, effective on the date of change.  In the event of any such change, we will post a notice on the website or mobile app that we have changed this Agreement. If you have an Outpost account, we may (but are not required to) provide you with notice of the change via the email address that we have on file for you.  You and we both understand that sometimes there are issues with email communications.  We are not responsible if any email notice gets caught by your Spam filter and you do not see it, if you have given us the wrong email address (or failed to update your address) or if there are other communications issues that prevent email from reaching you.  Therefore, we encourage you to frequently visit our website or mobile app to monitor any changes.  Your continued use of or access to the website, mobile app or Goods/Services following the posting of any changes to this Agreement constitute acceptance of those changes.</p>

    <p class="column small-12 medium-9 large-7"><b>Disputes.</b>  The formation, interpretation and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of the State of Wyoming without regard to its rules on conflict or choice of law.  The exclusive jurisdiction and venue for actions related to the subject matter of this Agreement shall be the state and federal courts located in Teton County, Wyoming, and you hereby submit to the personal jurisdiction of such courts.  You hereby waive any right to a jury trial in any proceeding arising out of or related to this Agreement.  </p>

    <p class="column small-12 medium-9 large-7"><b>Miscellaneous.</b>  a) if any portion of this Agreement is found unenforceable, the remaining portions will remain in full force and effect; b) if we fail to enforce this Agreement, it will not be considered a waiver; c) any amendment to or waiver of this Agreement must be made in writing and signed by us; d) you will not transfer any of your rights or obligations under this Agreement to anyone else without our prior written consent; e) all of our rights under this Agreement are freely assignable by us in connection with a merger, acquisition, or sale of assets, or by operation of law or otherwise; f) this Agreement does not confer any third party beneficiary rights; g) a printed version of this Agreement and of any related notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
</div>
</div>